### PR TITLE
Meta: Add LICENSE

### PR DESCRIPTION
**Pull request by Alf21**

### CODE REVIEW

**Review by Histalek — CHANGES_REQUESTED** [review]
We want to discuss this in a team meeting.
Therefore i'll throw in this as a blocker.

**Comment by AMastryukov** [comment]
This has been sitting here for quite some time. Perhaps we should have a quick thread to decide on this?

**Review by saibotk — APPROVED** [review]

**Review by saibotk — APPROVED** [review]

**Review by Histalek — APPROVED** [review]
Keep in mind that for the best possible effect a notice should be added to any source file as stated in lines 623-650 of the license.

**Review by Fires1 — APPROVED** [review]

**Review by TimGoll — APPROVED** [review]

**Review by mzegar — APPROVED** [review]

**Comment by Alf21** [comment]
Approving this as well with this comment as I can't approve my own PR via GitHub review ^^

**Comment by saibotk** [comment]
@Travh98 @pBinarySoul Would you two also agree to the license change?

**Comment by Travh98** [comment]
Looks good to me! I approve.

**Review by pBinarySoul — APPROVED** [review]

**Review by AMastryukov — APPROVED** [review]

**Review by Westsaid — APPROVED** [review]

**Pull request merged**
