### PR TITLE
Fea: Key Bindings

### PR DESCRIPTION
**Pull request by mzegar**
image

I'm pretty sure I didn't forget anything important.

### CODE REVIEW

**Comment by mzegar** [comment]
I think this is fine for now, I'd suggest putting up an issue for refactoring the menu system, it feels like the `Menu` class is a god class, we should probably break up all of these screens into sub classes.

**Comment by mzegar** [comment]
This needs a refactor, unable to get a scrolling list.

**Comment by Alf21** [comment]
Ah sad, thought about the same thing haha, would be good to have such a menu

**Comment by mzegar** [comment]
Yeah I'll keep the branch around and see if I can fix it up.

**Pull request closed without merging**
