### PR TITLE
Add TTTPanel to all Panels

### PR DESCRIPTION
**Pull request by Travh98**
I also set the IsShowing member variables everywhere that setClass("hide", true/false) was.
This is my first pull request and also first time using C#. I'm excited to help!

### CODE REVIEW

**Comment by mzegar** [comment]
Hey, thanks again for the PR.

Check out `InspectMenu.cs` there is an implementation for `IsShowing` we can remove, since we use the TTT Panel.

**Comment by mzegar** [comment]
It might be good to investigate why the inventory was not showing after it inherits from `TTTPanel`, because I think we would like to make `TTTPanel` a standard for all UI elements.

**Comment by Travh98** [comment]
Thank you for the review, I made the changes you mentioned.
As for the issue with Inventory not showing, I'll open a separate branch and troubleshoot that there.

**Review by mzegar — APPROVED** [review]
LGTM

**Comment by mzegar** [comment]
Spoke with Travh, figured out the issue with the inventory.

**Pull request merged**
