### PR TITLE
UI: Refactored folder structure

### PR DESCRIPTION
**Pull request by Alf21**
Based on #111

### CODE REVIEW

**Comment by mzegar** [comment]
You might be able to point this branch on GitHub to the branch it's based off of, that way people don't need to skim through code they've seen multiple times.

**Comment by Alf21** [comment]
> You might be able to point this branch on GitHub to the branch it's based off of, that way people don't need to skim through code they've seen multiple times.

What do you mean exactly? If I'd make this to a PR to the damage branch, I'd have to merge this into the damage branch and then into the master... That's why I added the comment and made it a Draft, so you don't need to review until the damage branch is done ^^

**Comment by mzegar** [comment]
@Alf21 Check out 

```
 mzegar changed the base branch from master to damage now
```

The PR now points to the branch it was worked off of .

**Review by mzegar — APPROVED** [review]
LGTM

**Review by saibotk — APPROVED** [review]

**Pull request merged**
