### PR TITLE
Refactor: Change ammo type to use enum

### PR DESCRIPTION
**Pull request by mzegar**
Wait till https://github.com/TTTReborn/tttreborn/pull/343 to merge

### CODE REVIEW

**Comment by mzegar** [comment]
Do we want to keep the library name from the previous PR? Currently not used for anything.

**Comment by Alf21** [comment]
Hmm just thought about the AmmoType var at all and it doesn't make a lot of sense to me... Theoretically, just the weapons need to have a connection to what ammo they need...

**Comment by mzegar** [comment]
> Hmm just thought about the AmmoType var at all and it doesn't make a lot of sense to me... Theoretically, just the weapons need to have a connection to what ammo they need...

It's a bit better in the sense that one enum defines the ammo type instead of ensuring that the string matches up in the definition of both `PistolAmmo.cs` and `Pistol.cs`. But yeah, I think having some way to ensure that both definitions depend on each other would be ideal.

**Comment by mzegar** [comment]
We should change this system as per Alfs suggestion, not wanting to actively work on this section at the moment though so closing this.

**Pull request closed without merging**
