### PR TITLE
Remove parent prefix

### PR DESCRIPTION
**Pull request by mzegar**

### CODE REVIEW

**Review by GravityWolfNotAmused — APPROVED** [review]
I am not sure why they weren't in the other PR, but yeah.

**Comment by mzegar** [comment]
> I am not sure why they weren't in the other PR, but yeah.

Messed up the merge on my end through the web interface.

**Comment by AMastryukov** [comment]
Looks good

**Review by AMastryukov — APPROVED** [review]
yes

**Pull request merged**
