### PR TITLE
Add a temporary post round screen

### PR DESCRIPTION
**Pull request by mzegar**
https://gyazo.com/d4b2a7d59c2f6972e02a394901032c45

### CODE REVIEW

**Comment by Westsaid** [comment]
Cool, I'll adjust the font-size a bit in a couple of hours...

**Comment by Westsaid** [comment]
I can't start the gamemode on this branch... @mzegar 
image

**Comment by mzegar** [comment]
> I can't start the gamemode on this branch... @mzegar
> image

Should be fixed now.

**Comment by Westsaid** [comment]
image
@mzegar  still got the same issue...
@Alf21 @TimGoll  do you also have this issue?

**Comment by mzegar** [comment]
Hmm, let me fix... maybe I didn't commit the changes.

**Comment by mzegar** [comment]
@Westsaid Now should be fixed, all that needed to be done is to remove line 0018 (as per your image)

**Comment by Westsaid** [comment]
Reduced Font-size to 28px
image

Good that you implemented the functionality for "windows" (Panel you can close on pressing X), tho I think in this case, where there is currently nothing to interact with, we should just display it like it was before. I really liked that this would keep you ingame and the panel would only display as long as its needed...

**Comment by mzegar** [comment]
@Westsaid Yeah I can revert back no problem. I just wanted to add that since we will probably get to a point where the user can open/close the results menu at their own will (since it'll at some point be populated with way more content).

**Comment by mzegar** [comment]
Apologies for not getting around and changing this, just been taking a tiny break from development.

**Comment by mzegar** [comment]
@Westsaid Do we want to close this PR for now? We can consider this at a future point.

**Comment by Alf21** [comment]
I like these changes

**Comment by Westsaid** [comment]
Sorry for not coming to this for so long... it's merged now

**Review by Westsaid — APPROVED** [review]

**Pull request merged**
